#!/usr/bin/env python3
"""
download_manual_subtitles.py
=============================
Downloads only manually written subtitles (i.e. human-made) from YouTube,
skipping any video that only has auto-generated captions.

yt-dlp exposes two distinct fields in its JSON metadata:
  - "subtitles"          : manually written tracks  <- we want these
  - "automatic_captions" : auto-generated by YouTube <- we skip these

Usage:
    python download_manual_subtitles.py \
        --urls urls.txt \
        --out-dir subtitles/ \
        --lang en \
        --workers 8 \
        --log skipped.txt

Requirements:
    pip install yt-dlp tqdm
"""
import argparse
import json
import logging
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from tqdm import tqdm

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


def fetch_metadata(url: str) -> dict | None:
    """Pull JSON metadata for a single video without downloading anything.
    Returns None if yt-dlp fails (deleted video, private, geo-blocked…)."""
    result = subprocess.run(
        ["yt-dlp", "--dump-json", "--no-playlist", url],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def has_manual_subtitles(meta: dict, lang: str) -> bool:
    """Return True only if the video has at least one manually written
    subtitle track for the requested language.
    The 'subtitles' field contains human-made tracks; 'automatic_captions'
    contains YouTube's ASR output — we never touch the latter."""
    subs = meta.get("subtitles", {})
    # yt-dlp sometimes uses e.g. "en-US" or "en-GB" — check prefix too
    return any(k == lang or k.startswith(f"{lang}-") for k in subs)


def download_subtitles(url: str, out_dir: Path, lang: str) -> bool:
    """Download the manual subtitle file for one video.
    Saves as <video_id>.<lang>.vtt inside out_dir/<channel>/."""
    result = subprocess.run(
        [
            "yt-dlp",
            "--write-subs",          # manual subtitles only — no --write-auto-subs
            "--skip-download",       # audio/video not needed here
            "--sub-lang", lang,
            "--sub-format", "vtt",
            "--no-playlist",
            "-o", str(out_dir / "%(channel)s" / "%(id)s" / "%(id)s.%(ext)s"),
            url,
        ],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def process_url(url: str, out_dir: Path, lang: str):
    """Full pipeline for one URL: fetch metadata → check for manual subs
    → download or skip. Returns a status string for logging."""
    url = url.strip()
    if not url or url.startswith("#"):
        return url, "skipped_comment"

    meta = fetch_metadata(url)
    if meta is None:
        return url, "unavailable"

    video_id = meta.get("id", url)
    channel = meta.get("channel", "unknown")

    if not has_manual_subtitles(meta, lang):
        # only auto-generated captions exist — not reliable enough for ASR training
        return url, f"no_manual_subs  [{channel}] {video_id}"

    success = download_subtitles(url, out_dir, lang)
    if success:
        return url, f"ok  [{channel}] {video_id}"
    else:
        return url, f"download_failed  [{channel}] {video_id}"


def main():
    parser = argparse.ArgumentParser(
        description="Download only human-written subtitles from a list of YouTube URLs"
    )
    parser.add_argument("--urls", required=True,
                        help="Text file with one YouTube URL per line (output of extract_youtube_urls.py)")
    parser.add_argument("--out-dir", default="subtitles",
                        help="Root directory for downloaded subtitle files")
    parser.add_argument("--lang", default="en",
                        help="Subtitle language code (default: en)")
    parser.add_argument("--workers", type=int, default=8,
                        help="Number of parallel download threads")
    parser.add_argument("--log", default="subtitle_download.log",
                        help="File to write per-video status (ok / no_manual_subs / unavailable…)")
    args = parser.parse_args()

    urls = [l.strip() for l in Path(args.urls).read_text().splitlines()
            if l.strip() and not l.startswith("#")]
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    log.info(f"{len(urls)} URLs to process  |  language: {args.lang}  |  workers: {args.workers}")

    counts = {"ok": 0, "no_manual_subs": 0, "unavailable": 0, "download_failed": 0}

    with open(args.log, "w", encoding="utf-8") as logfile, \
         ThreadPoolExecutor(max_workers=args.workers) as pool:

        futures = {pool.submit(process_url, url, out_dir, args.lang): url for url in urls}

        for future in tqdm(as_completed(futures), total=len(futures), desc="videos"):
            url, status = future.result()
            logfile.write(f"{status}\t{url}\n")
            logfile.flush()

            # bucket the status for the final summary
            key = status.split()[0] if status else "unknown"
            if key in counts:
                counts[key] += 1
            else:
                counts["ok"] += 1  # catch-all for "ok [channel] ..." lines

    log.info("Done.")
    log.info(f"  downloaded (manual subs found) : {counts['ok']}")
    log.info(f"  skipped (auto-only)            : {counts['no_manual_subs']}")
    log.info(f"  unavailable (deleted/private)  : {counts['unavailable']}")
    log.info(f"  download errors                : {counts['download_failed']}")
    log.info(f"  full log written to            : {args.log}")


if __name__ == "__main__":
    main()